sudo: false
language: node_js
node_js:
- node
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_ce88f7f76251_key -iv $encrypted_ce88f7f76251_iv
  -in client-secret.json.enc -out client-secret.json -d
- openssl aes-256-cbc -K $encrypted_052a7cd3d4e4_key -iv $encrypted_052a7cd3d4e4_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: fcps-distribution
  default: true
